<?php

namespace App\Dto\Api\Request;

use App\Validator as AppAssert;
use Nelmio\ApiDocBundle\Annotation\Model;
use OpenApi\Attributes as OA;
use Symfony\Component\Serializer\Attribute\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[OA\Schema(
    description: 'Payload pour créer un désordre.',
    required: ['identifiant'],
)]
#[Groups(groups: ['Default', 'false'])]
#[AppAssert\ApiDesordreRequest]
class DesordreRequest implements RequestInterface
{
    #[OA\Property(
        description: 'Identifiant du désordre.
                     <br>Voir le <a href="/doc-api/desordres" target="_blank">tableau de référence des désordres</a>.',
        example: 'desordres_logement_humidite_salle_de_bain',
    )]
    #[Assert\NotBlank]
    #[Assert\Choice(
        choices: [
            'desordres_batiment_proprete_interieur',
            'desordres_batiment_proprete_facades',
            'desordres_batiment_proprete_parties_communes',
            'desordres_batiment_proprete_local_poubelles',
            'desordres_batiment_eau_pas_eau_potable',
            'desordres_batiment_eau_evacuation_KO',
            'desordres_batiment_eau_pas_eau_chaude',
            'desordres_batiment_eau_pas_evacuation_eaux_pluie',
            'desordres_batiment_isolation_murs',
            'desordres_batiment_isolation_porte_fenetres',
            'desordres_batiment_isolation_dernier_etage_toit',
            'desordres_batiment_isolation_infiltration_eau',
            'desordres_batiment_maintenance_ascenseur',
            'desordres_batiment_maintenance_petites_reparations',
            'desordres_batiment_nuisibles_cafards',
            'desordres_batiment_nuisibles_rongeurs',
            'desordres_batiment_nuisibles_punaises',
            'desordres_batiment_nuisibles_autres',
            'desordres_batiment_securite_sol',
            'desordres_batiment_securite_elements_toit',
            'desordres_batiment_securite_toit',
            'desordres_batiment_securite_escalier',
            'desordres_batiment_securite_murs_fissures',
            'desordres_batiment_securite_balcons',
            'desordres_batiment_incendie_porte_coupe_feu',
            'desordres_batiment_incendie_odeur_gaz',
            'desordres_batiment_accessibilite_friche',
            'desordres_batiment_accessibilite_eclairage',
            'desordres_batiment_accessibilite_acces_batiment',
            'desordres_batiment_bruit_exterieur',
            'desordres_batiment_bruit_interieur',
            'desordres_type_composition_logement_sous_combles',
            'desordres_type_composition_logement_sous_sol',
            'desordres_type_composition_logement_piece_unique_superficie',
            'desordres_type_composition_logement_plusieurs_pieces_aucune_piece_9',
            'desordres_type_composition_logement_cuisine',
            'desordres_type_composition_logement_douche',
            'desordres_type_composition_logement_wc',
            'desordres_type_composition_logement_suroccupation',
            'desordres_logement_eau_eau_potable',
            'desordres_logement_eau_evacuation',
            'desordres_logement_eau_eau_chaude',
            'desordres_logement_aeration_aucune_aeration',
            'desordres_logement_aeration_ventilation_defectueuse',
            'desordres_logement_chauffage_details_fenetres_permeables',
            'desordres_logement_chauffage_type_aucun',
            'desordres_logement_chauffage_details_difficultes_chauffage',
            'desordres_logement_chauffage_details_chauffage_KO',
            'desordres_logement_chauffage_details_chauffage_dangereux',
            'desordres_logement_humidite_piece_a_vivre',
            'desordres_logement_humidite_cuisine',
            'desordres_logement_humidite_salle_de_bain',
            'desordres_logement_securite_sol_glissant',
            'desordres_logement_securite_sol_dangereux',
            'desordres_logement_securite_balcons',
            'desordres_logement_securite_gaz',
            'desordres_logement_securite_plomb',
            'desordres_logement_electricite_pas_electricite',
            'desordres_logement_electricite_pas_compteur',
            'desordres_logement_electricite_installation_dangereuse',
            'desordres_logement_electricite_manque_prises',
            'desordres_logement_nuisibles_cafards',
            'desordres_logement_nuisibles_rongeurs',
            'desordres_logement_nuisibles_punaises',
            'desordres_logement_nuisibles_autres',
            'desordres_logement_bruit_exterieur',
            'desordres_logement_bruit_voisins',
            'desordres_logement_lumiere_pas_lumiere',
            'desordres_logement_lumiere_pas_volets',
            'desordres_logement_lumiere_plafond_trop_bas',
            'desordres_logement_proprete',
        ],
    )]
    public ?string $identifiant = null;

    /** @var array<string> */
    #[OA\Property(
        description: 'Liste des identifiants des précisions du désordre.
                     <br><strong>⚠️ Obligatoire dans le cas où des précisions existent pour l\'identifiant soumis.</strong>
                     <br>Voir le <a href="/doc-api/desordres" target="_blank">tableau de référence des désordres</a>.',
        type: 'array',
        items: new OA\Items(type: 'string'),
        example: [
            'desordres_logement_humidite_salle_de_bain_details_machine_non',
            'desordres_logement_humidite_salle_de_bain_details_moisissure_apres_nettoyage_oui',
            'desordres_logement_humidite_salle_de_bain_details_fuite_non',
        ],
    )]
    #[Assert\All([
        new Assert\Choice(choices: [
            'desordres_batiment_isolation_dernier_etage_toit_sous_toit_non',
            'desordres_batiment_isolation_dernier_etage_toit_dernier_etage',
            'desordres_batiment_isolation_dernier_etage_toit_sous_combles',
            'desordres_batiment_isolation_dernier_etage_toit_maison_individuelle',
            'desordres_batiment_isolation_infiltration_eau_au_sol_non',
            'desordres_batiment_isolation_infiltration_eau_sous_sol',
            'desordres_batiment_isolation_infiltration_eau_rdc',
            'desordres_batiment_isolation_infiltration_eau_maison_individuelle',
            'desordres_batiment_securite_sol_details_plancher_abime',
            'desordres_batiment_securite_sol_details_plancher_effondre',
            'desordres_batiment_securite_escalier_details_utilisable',
            'desordres_batiment_securite_escalier_details_dangereux',
            'desordres_batiment_securite_murs_fissures_details_mur_porteur_oui',
            'desordres_batiment_securite_murs_fissures_details_mur_porteur_non',
            'desordres_batiment_securite_murs_fissures_details_mur_porteur_nsp',
            'desordres_type_composition_logement_cuisine_collective_oui',
            'desordres_type_composition_logement_cuisine_collective_non',
            'desordres_type_composition_logement_douche_collective_oui',
            'desordres_type_composition_logement_douche_collective_non',
            'desordres_type_composition_logement_wc_collectif_oui',
            'desordres_type_composition_logement_wc_collectif_non',
            'desordres_type_composition_logement_wc_cuisine_ensemble',
            'desordres_type_composition_logement_suroccupation_non_allocataire',
            'desordres_type_composition_logement_suroccupation_allocataire',
            'desordres_logement_aeration_aucune_aeration_pieces_tout',
            'desordres_logement_aeration_aucune_aeration_pieces_piece_a_vivre',
            'desordres_logement_aeration_aucune_aeration_pieces_cuisine',
            'desordres_logement_aeration_aucune_aeration_pieces_salle_de_bain',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_tout_nettoyage_oui',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_piece_a_vivre_nettoyage_oui',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_cuisine_nettoyage_oui',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_salle_de_bain_nettoyage_oui',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_tout_nettoyage_non',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_piece_a_vivre_nettoyage_non',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_cuisine_nettoyage_non',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_salle_de_bain_nettoyage_non',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_tout_nettoyage_nsp',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_piece_a_vivre_nettoyage_nsp',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_cuisine_nettoyage_nsp',
            'desordres_logement_aeration_ventilation_defectueuse_details_pieces_salle_de_bain_nettoyage_nsp',
            'desordres_logement_chauffage_details_fenetres_permeables_pieces_tout',
            'desordres_logement_chauffage_details_fenetres_permeables_pieces_piece_a_vivre',
            'desordres_logement_chauffage_details_fenetres_permeables_pieces_cuisine',
            'desordres_logement_chauffage_details_fenetres_permeables_pieces_salle_de_bain',
            'desordres_logement_chauffage_type_aucun_pieces_tout',
            'desordres_logement_chauffage_type_aucun_pieces_piece_a_vivre',
            'desordres_logement_chauffage_type_aucun_pieces_cuisine',
            'desordres_logement_chauffage_type_aucun_pieces_salle_de_bain',
            'desordres_logement_chauffage_details_difficultes_chauffage_pieces_tout',
            'desordres_logement_chauffage_details_difficultes_chauffage_pieces_piece_a_vivre',
            'desordres_logement_chauffage_details_difficultes_chauffage_pieces_cuisine',
            'desordres_logement_chauffage_details_difficultes_chauffage_pieces_salle_de_bain',
            'desordres_logement_chauffage_details_chauffage_KO_pieces_tout',
            'desordres_logement_chauffage_details_chauffage_KO_pieces_piece_a_vivre',
            'desordres_logement_chauffage_details_chauffage_KO_pieces_cuisine',
            'desordres_logement_chauffage_details_chauffage_KO_pieces_salle_de_bain',
            'desordres_logement_humidite_piece_a_vivre_details_machine_oui',
            'desordres_logement_humidite_piece_a_vivre_details_machine_non',
            'desordres_logement_humidite_piece_a_vivre_details_machine_nsp',
            'desordres_logement_humidite_piece_a_vivre_details_moisissure_apres_nettoyage_oui',
            'desordres_logement_humidite_piece_a_vivre_details_moisissure_apres_nettoyage_non',
            'desordres_logement_humidite_piece_a_vivre_details_moisissure_apres_nettoyage_nsp',
            'desordres_logement_humidite_piece_a_vivre_details_fuite_oui',
            'desordres_logement_humidite_piece_a_vivre_details_fuite_non',
            'desordres_logement_humidite_cuisine_details_machine_oui',
            'desordres_logement_humidite_cuisine_details_machine_non',
            'desordres_logement_humidite_cuisine_details_machine_nsp',
            'desordres_logement_humidite_cuisine_details_moisissure_apres_nettoyage_oui',
            'desordres_logement_humidite_cuisine_details_moisissure_apres_nettoyage_non',
            'desordres_logement_humidite_cuisine_details_moisissure_apres_nettoyage_nsp',
            'desordres_logement_humidite_cuisine_details_fuite_oui',
            'desordres_logement_humidite_cuisine_details_fuite_non',
            'desordres_logement_humidite_salle_de_bain_details_machine_oui',
            'desordres_logement_humidite_salle_de_bain_details_machine_non',
            'desordres_logement_humidite_salle_de_bain_details_machine_nsp',
            'desordres_logement_humidite_salle_de_bain_details_moisissure_apres_nettoyage_oui',
            'desordres_logement_humidite_salle_de_bain_details_moisissure_apres_nettoyage_non',
            'desordres_logement_humidite_salle_de_bain_details_moisissure_apres_nettoyage_nsp',
            'desordres_logement_humidite_salle_de_bain_details_fuite_oui',
            'desordres_logement_humidite_salle_de_bain_details_fuite_non',
            'desordres_logement_securite_sol_glissant_pieces_tout',
            'desordres_logement_securite_sol_glissant_pieces_piece_a_vivre',
            'desordres_logement_securite_sol_glissant_pieces_cuisine',
            'desordres_logement_securite_sol_glissant_pieces_salle_de_bain',
            'desordres_logement_securite_sol_dangereux_pieces_tout',
            'desordres_logement_securite_sol_dangereux_pieces_piece_a_vivre',
            'desordres_logement_securite_sol_dangereux_pieces_cuisine',
            'desordres_logement_securite_sol_dangereux_pieces_salle_de_bain',
            'desordres_logement_securite_balcons_pieces_tout',
            'desordres_logement_securite_balcons_pieces_piece_a_vivre',
            'desordres_logement_securite_balcons_pieces_cuisine',
            'desordres_logement_securite_balcons_pieces_salle_de_bain',
            'desordres_logement_securite_plomb_pieces_tout_diagnostique_oui',
            'desordres_logement_securite_plomb_pieces_piece_a_vivre_diagnostique_oui',
            'desordres_logement_securite_plomb_pieces_cuisine_diagnostique_oui',
            'desordres_logement_securite_plomb_pieces_salle_de_bain_diagnostique_oui',
            'desordres_logement_securite_plomb_pieces_tout_diagnostique_non',
            'desordres_logement_securite_plomb_pieces_piece_a_vivre_diagnostique_non',
            'desordres_logement_securite_plomb_pieces_cuisine_diagnostique_non',
            'desordres_logement_securite_plomb_pieces_salle_de_bain_diagnostique_non',
            'desordres_logement_securite_plomb_pieces_tout_diagnostique_nsp',
            'desordres_logement_securite_plomb_pieces_piece_a_vivre_diagnostique_nsp',
            'desordres_logement_securite_plomb_pieces_cuisine_diagnostique_nsp',
            'desordres_logement_securite_plomb_pieces_salle_de_bain_diagnostique_nsp',
            'desordres_logement_electricite_manque_prises_details_multiprises_oui',
            'desordres_logement_electricite_manque_prises_details_multiprises_non',
            'desordres_logement_electricite_manque_prises_details_multiprises_nsp',
            'desordres_logement_nuisibles_cafards_details_date_before_movein',
            'desordres_logement_nuisibles_cafards_details_date_after_movein',
            'desordres_logement_nuisibles_cafards_details_date_nsp',
            'desordres_logement_nuisibles_rongeurs_details_date_before_movein',
            'desordres_logement_nuisibles_rongeurs_details_date_after_movein',
            'desordres_logement_nuisibles_rongeurs_details_date_nsp',
            'desordres_logement_nuisibles_punaises_details_date_before_movein',
            'desordres_logement_nuisibles_punaises_details_date_after_movein',
            'desordres_logement_nuisibles_punaises_details_date_nsp',
            'desordres_logement_nuisibles_autres_details_date_before_movein',
            'desordres_logement_nuisibles_autres_details_date_after_movein',
            'desordres_logement_nuisibles_autres_details_date_nsp',
            'desordres_logement_lumiere_pas_lumiere_pieces_tout',
            'desordres_logement_lumiere_pas_lumiere_pieces_piece_a_vivre',
            'desordres_logement_lumiere_pas_lumiere_pieces_cuisine',
            'desordres_logement_lumiere_pas_lumiere_pieces_salle_de_bain',
            'desordres_logement_lumiere_pas_volets_pieces_tout',
            'desordres_logement_lumiere_pas_volets_pieces_piece_a_vivre',
            'desordres_logement_lumiere_pas_volets_pieces_cuisine',
            'desordres_logement_lumiere_pas_volets_pieces_salle_de_bain',
            'desordres_logement_lumiere_plafond_trop_bas_piece_a_vivre',
            'desordres_logement_lumiere_plafond_trop_bas_cuisine',
            'desordres_logement_lumiere_plafond_trop_bas_salle_de_bain',
            'desordres_logement_lumiere_plafond_trop_bas_toutes_pieces',
            'desordres_logement_proprete_pieces_tout',
            'desordres_logement_proprete_pieces_piece_a_vivre',
            'desordres_logement_proprete_pieces_cuisine',
            'desordres_logement_proprete_pieces_salle_de_bain',
        ]),
    ])]
    public array $precisions = [];

    /** @var array<DesordrePrecisionLibreRequest> $precisionLibres */
    #[OA\Property(
        description: 'Liste de précision libre concernant le désordre.',
        type: 'array',
        items: new OA\Items(ref: new Model(type: DesordrePrecisionLibreRequest::class))
    )]
    #[Assert\Valid]
    public array $precisionLibres = [];
}
