# https://symfony.com/bundles/DoctrineBundle/current/configuration.html
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                server_version: '8.0.40'
                use_savepoints: false
                charset: utf8mb4
                # All view or table as well start by view will be ignored by the schema tool.
                schema_filter: ~^(?!view_)~
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
        types:
            type_composition_logement: App\Entity\DoctrineType\Signalement\TypeCompositionLogementType
            situation_foyer: App\Entity\DoctrineType\Signalement\SituationFoyerType
            information_procedure: App\Entity\DoctrineType\Signalement\InformationProcedureType
            information_complementaire: App\Entity\DoctrineType\Signalement\InformationComplementaireType
    orm:
        controller_resolver:
            auto_mapping: false
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
                IFNULL: DoctrineExtensions\Query\Mysql\IfNull
                DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                DATE: DoctrineExtensions\Query\Mysql\Date
                NOW: DoctrineExtensions\Query\Mysql\Now
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
                JSON_CONTAINS_PATH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContainsPath
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                JSON_ARRAY: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonArray
                JSON_OBJECT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonObject
                IF: DoctrineExtensions\Query\Mysql\IfElse
                SUBSTRING_INDEX: DoctrineExtensions\Query\Mysql\SubstringIndex
                CAST: DoctrineExtensions\Query\Mysql\Cast
                GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                CONCAT_WS: DoctrineExtensions\Query\Mysql\ConcatWs
                REGEXP: DoctrineExtensions\Query\Mysql\Regexp

when@test:
    doctrine:
        dbal:
            connections:
                default:
                    use_savepoints: true
