framework:
    html_sanitizer:
        sanitizers:
            app.message_sanitizer:
                allow_safe_elements: true
                allow_relative_links: true
                allow_elements:
                    a: ['class', 'target', 'href', 'title', 'rel']
                    ul: ''
                    ol: ''
                    li: ''
                    strong: ''
                    em: ''
                    span: ''
                    div: ''
                    table: ''
                    thead: ''
                    tbody: ''
                    tr: ''
                    th: ''
                    td: ''
                drop_elements: ['img']
                max_input_length: 20000000
