framework:
    html_sanitizer:
        sanitizers:
            app.message_sanitizer:
                allow_relative_links: true
                allow_elements:
                    a: ['class', 'target', 'href', 'title', 'rel']
                    ul: ''
                    ol: ''
                    li: ''
                    strong: ''
                    em: ''
                    br: ''
                    span: ''
                    div: ''
                block_elements: ['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6']
