framework:
    rate_limiter:
        contact_form:
            policy: 'fixed_window'
            limit: '%env(int:FORMS_SUBMIT_LIMITER_LIMIT)%'
            interval: '%env(FORMS_SUBMIT_LIMITER_INTERVAL)%'
        ask_link_form:
            policy: 'fixed_window'
            limit: '%env(int:FORMS_SUBMIT_LIMITER_LIMIT)%'
            interval: '%env(FORMS_SUBMIT_LIMITER_INTERVAL)%'
        login_activation_form:
            policy: 'fixed_window'
            limit: '%env(int:FORMS_SUBMIT_LIMITER_LIMIT)%'
            interval: '%env(FORMS_SUBMIT_LIMITER_INTERVAL)%'
        login_password_form:
            policy: 'fixed_window'
            limit: '%env(int:FORMS_SUBMIT_LIMITER_LIMIT)%'
            interval: '%env(FORMS_SUBMIT_LIMITER_INTERVAL)%'
        api_limiter: 
            policy: 'fixed_window'
            limit: '%env(int:API_LIMITER_LIMIT)%'
            interval: '%env(API_LIMITER_INTERVAL)%'