framework:
    rate_limiter:
        contact_form:
            policy: 'fixed_window'
            limit: '%env(int:CONTACT_FORM_LIMITER_LIMIT)%'
            interval: '%env(CONTACT_FORM_LIMITER_INTERVAL)%'