when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry
        options:
          environment: '%kernel.environment%'

    monolog:
      handlers:
        sentry:
          type: sentry
          level: !php/const Monolog\Logger::ERROR
          hub_id: Sentry\State\HubInterface

    services:
      Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }


#        If you are using Monolog, you also need these additional configuration and services to log the errors correctly:
#        https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
#        register_error_listener: false

#        monolog:
#            handlers:
#                sentry:
#                    type: service
#                    id: Sentry\Monolog\Handler

#        services:
#            Sentry\Monolog\Handler:
#                arguments:
#                    $hub: '@Sentry\State\HubInterface'
#                    $level: !php/const Monolog\Logger::ERROR
#                    $bubble: false
