# docker-compose.yml
version: "3.8"

services:
  matomo_db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - dbmatomo:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=matomo
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./.docker/matomo/db.env

  matomo_app:
    image: matomo
    restart: always
    volumes:
      - matomo:/var/www/html:z
      - ./.docker/matomo/update-config-ini.sh:/var/www/html/update-config-ini.sh:z
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
    env_file:
      - ./.docker/matomo/db.env
    ports:
      - 8083:80

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - 3007:3000

  cypress:
    image: cypress/base:latest

volumes:
  dbmatomo:
  matomo:
