# docker-compose.yml

services:
  matomo_db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - dbmatomo:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=matomo
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./.docker/matomo/db.env

  matomo_app:
    image: matomo
    restart: always
    volumes:
      - matomo:/var/www/html
      - ./.docker/matomo/update-config-ini.sh:/var/www/html/update-config-ini.sh
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
    env_file:
      - ./.docker/matomo/db.env
    ports:
      - 8083:80

  metabase_db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase-local
    volumes:
      - metabase-db:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    restart: always
    depends_on:
      - metabase_db
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase-local
      MB_DB_HOST: metabase_db
    ports:
      - "127.0.0.1:3007:3000"

volumes:
  dbmatomo:
  matomo:
  metabase-db:
