# Expose your documentation as JSON swagger compliant
app.redocly_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.redocly }

app.swagger_ui:
    path: /api/doc/swagger
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
