export interface Filters {
  [key: string]: any
}

export const SEARCH_FILTERS = [
  { type: 'text', name: 'territoire', showOptions: false, defaultValue: null },
  { type: 'text', name: 'searchTerms', showOptions: false, defaultValue: null },
  { type: 'text', name: 'status', showOptions: false, defaultValue: null },
  { type: 'text', name: 'page', showOptions: false, defaultValue: null },
  { type: 'text', name: 'sortBy', showOptions: false, defaultValue: null },
  { type: 'text', name: 'direction', showOptions: false, defaultValue: null },
  { type: 'text', name: 'procedure', showOptions: true, defaultValue: null },
  { type: 'text', name: 'procedureConstatee', showOptions: true, defaultValue: null },  
  { type: 'text', name: 'visiteStatus', showOptions: true, defaultValue: null },
  { type: 'text', name: 'statusAffectation', showOptions: true, defaultValue: null },
  { type: 'text', name: 'typeDernierSuivi', showOptions: true, defaultValue: null },
  { type: 'text', name: 'criticiteScoreMin', showOptions: true, defaultValue: null },
  { type: 'text', name: 'criticiteScoreMax', showOptions: true, defaultValue: null },
  { type: 'text', name: 'typeDeclarant', showOptions: true, defaultValue: null },
  { type: 'text', name: 'natureParc', showOptions: true, defaultValue: null },
  { type: 'text', name: 'bailleurSocial', showOptions: true, defaultValue: null },
  { type: 'text', name: 'allocataire', showOptions: true, defaultValue: null },
  { type: 'text', name: 'enfantsM6', showOptions: true, defaultValue: null },
  { type: 'text', name: 'situation', showOptions: true, defaultValue: null },
  { type: 'text', name: 'createdFrom', showOptions: false, defaultValue: null },
  { type: 'text', name: 'usagerAbandonProcedure', showOptions: false, defaultValue: null },
  { type: 'text', name: 'showMyAffectationOnly', showOptions: true, defaultValue: null },
  { type: 'text', name: 'showMySignalementsOnly', showOptions: false, defaultValue: null },
  { type: 'text', name: 'isMessagePostCloture', showOptions: false, defaultValue: null },
  { type: 'text', name: 'isNouveauMessage', showOptions: false, defaultValue: null },
  { type: 'text', name: 'isMessageWithoutResponse', showOptions: false, defaultValue: null },
  { type: 'text', name: 'isDossiersSansActivite', showOptions: false, defaultValue: null },
  { type: 'text', name: 'isEmailAVerifier', showOptions: false, defaultValue: null },  
  { type: 'text', name: 'isDossiersSansAgent', showOptions: false, defaultValue: null },
  { type: 'text', name: 'isActiviteRecente', showOptions: false, defaultValue: null },
  { type: 'text', name: 'showWithoutAffectationOnly', showOptions: true, defaultValue: null },
  { type: 'text', name: 'isImported', showOptions: false, defaultValue: null },
  { type: 'text', name: 'isZonesDisplayed', showOptions: false, defaultValue: null },
  { type: 'collection', name: 'communes', showOptions: false, defaultValue: null },
  { type: 'collection', name: 'epcis', showOptions: false, defaultValue: null },
  { type: 'collection', name: 'etiquettes', showOptions: true, defaultValue: null },
  { type: 'collection', name: 'zones', showOptions: true, defaultValue: null },
  { type: 'collection', name: 'partenaires', showOptions: true, defaultValue: null },
  { type: 'date', name: 'dateDepotDebut', showOptions: true, defaultValue: null },
  { type: 'date', name: 'dateDernierSuiviDebut', showOptions: true, defaultValue: null },
  { type: 'text', name: 'motifCloture', showOptions: true, defaultValue: null },
  { type: 'text', name: 'relanceUsagerSansReponse', showOptions: false, defaultValue: null }
]
