<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Entity\Enum\PartnerType;
use App\Entity\Enum\Qualification;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20230407151135 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Affect type to partner';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('UPDATE partner SET type = "'.PartnerType::COMMUNE_SCHS->name.'" WHERE is_commune=1');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::ADIL->name.'" WHERE lower(nom) LIKE "%adil%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ADIL->name.'" WHERE nom="A.D.I.L."');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ADIL->name.'" WHERE nom="ADMIL"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::ARS->name.'" WHERE lower(nom) LIKE "%ars%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ARS->name.'" WHERE nom="A.R.S."');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ARS->name.'" WHERE nom="Dt-arS 54"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::CAF_MSA->name.'" WHERE lower(nom) LIKE "%caf%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CAF_MSA->name.'" WHERE lower(nom) LIKE "%msa%"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::CCAS->name.'" WHERE lower(nom) LIKE "%ccas%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CCAS->name.'" WHERE nom="CIAS CAPA"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::DDETS->name.'" WHERE lower(nom) LIKE "%ddets%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DDETS->name.'" WHERE nom="CDC Blaye"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DDETS->name.'" WHERE nom="CDC Estuaire"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DDETS->name.'" WHERE nom="CDC Latitude Nord Gironde"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DDETS->name.'" WHERE nom="Grand Cubzaguais CDC"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::DDT_M->name.'" WHERE lower(nom) LIKE "%ddt%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DDT_M->name.'" WHERE nom="Commission de qualification du PDLHIml 33"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DDT_M->name.'" WHERE nom="DEAL"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::OPERATEUR_VISITES_ET_TRAVAUX->name.'" WHERE lower(nom) LIKE "%urbanis%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::OPERATEUR_VISITES_ET_TRAVAUX->name.'" WHERE lower(nom) LIKE "%soliha%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::OPERATEUR_VISITES_ET_TRAVAUX->name.'" WHERE lower(nom) LIKE "%opérateur%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::OPERATEUR_VISITES_ET_TRAVAUX->name.'" WHERE nom="POLYGONE"');

        $competenceVisite = [Qualification::VISITES];
        $this->addSql('UPDATE partner SET competence = \''.json_encode($competenceVisite).'\' WHERE lower(nom) LIKE "%urbanis%"');
        $this->addSql('UPDATE partner SET competence = \''.json_encode($competenceVisite).'\' WHERE lower(nom) LIKE "%soliha%"');
        $this->addSql('UPDATE partner SET competence = \''.json_encode($competenceVisite).'\' WHERE lower(nom) LIKE "%opérateur%"');
        $this->addSql('UPDATE partner SET competence = \''.json_encode($competenceVisite).'\' WHERE nom="POLYGONE"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::POLICE_GENDARMERIE->name.'" WHERE lower(nom) LIKE "%police%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::POLICE_GENDARMERIE->name.'" WHERE lower(nom) LIKE "%gendarmerie%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::POLICE_GENDARMERIE->name.'" WHERE nom="PM de Ligueil"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::PREFECTURE->name.'" WHERE lower(nom) LIKE "%prefecture%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::PREFECTURE->name.'" WHERE lower(nom) LIKE "%préfecture%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::PREFECTURE->name.'" WHERE nom="Sous-Pref Dreux"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::TRIBUNAL->name.'" WHERE lower(nom) LIKE "%tribunal%"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::TRIBUNAL->name.'" WHERE lower(nom) LIKE "%parquet%"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Association Espoir 54 - EPSIL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="FAMILLE & PROVENCE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="ADIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="ADOMA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="APPORT SANTE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="ALPIL DMLHI"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="ALPIL INCURIE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Bertrand MEAR - Directeur - Heol"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Cathy PENNEC - Educatrice Spécialisée ASLL - La Croix rouge"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Christelle MERDY - Assocation ASAD"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="CLIC COOMAID"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Fondation Abbé Pierre"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="France Victimes Siavic"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Interfaces"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Lucie KERAUDREN - Educatrice - Association Croix Rouge - ASLL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Marjolaine BOLZER - Mission Locale pays de Conouaille"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Thumette RIOUAL - Educatrice - Association Croix-Rouge - ASLL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="UDAF 08"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Udaf"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::ASSOCIATION->name.'" WHERE nom="Valérie BOULC\'H - CLCV"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Administrateurs Histologe ALL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Altair"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Compagnons Bâtisseurs de Provence"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="CMS de SISTERON"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="SOLIHA-DALO"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="ANCB"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="ANCOLS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="ATEL - SERVICES SOCIAUX"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Claire LABEL - ALECOB"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Clic Val de Durance"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Collectif SIAO48"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Compagnons Bâtiseurs de Bretagne"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Compagnons batisseurs"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="DDCS du Nord"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="FONDS SOLIDARITE LOGEMENT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Oriane MORVAN - ALECOB"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="PLSF (S. TORNAVACCA)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::AUTRE->name.'" WHERE nom="Pôle Logement Social et Foncier"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Bailleur social"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Bailleur social"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="bailleurs sociaux GDH"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="bailleurs sociaux ORVITIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="bailleurs sociaux CDC HABITAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="bailleurs sociaux HABELLIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="bailleurs sociaux ICF HABITAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Bailleur social - PLURIAL NOVILIA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Bailleur social - NOV\'HABITAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Bailleur social - REIMS HABITAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Bailleur social - FOYER REMOIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Bailleur social - ICF"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Bailleur social"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Pau Béarn Habitat (bailleur social)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="3F SUD"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="HABITATIONS HAUTE PROVENCE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="LOGIAH 04"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="UNICIL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Ardèche habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="HABITAT08"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="13 HABITAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Bailleur"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Ouest Provence Habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="MARSEILLE HABITAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Habitat Marseille Provence"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="HABITAT 17"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Hateis Habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Val de berry - propriétaire bailleur"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="France Loire - Propriétaire bailleur"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="CORREZE HABITAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Habitat Drouais"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Habitat Eurélien"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Chartres Métropole Habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Nogent-Perche-Habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SA Eure-et-Loir Habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="ERILIA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="ERILIA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="ESH LOZERE HABITATIONS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="FAMILLE ET PROVENCE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="France Loire - Relogement"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Espacil Habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Habitat du Nord"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="HOMY"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="ICF HABITAT NORD-EST (bailleur social)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="ICF Méditerranée"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="IMMOBILIERE ATLANTIC AMENAGEMENT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="LOGIREM"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Logis Méditerranée"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SA HLM AIGUILLON CONSTRUCTION"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="ESPACIL HABITAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="NEOTOA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Alliade Habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="OPH 66"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="OPH CDA LA ROCHELLE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="OPH de la Meuse"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Partenord"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="PROCIVIS-SACICAP BSA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SA EMERAUDE HABITATION"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SA LA RANCE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SA la Roseraie"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SA LES FOYERS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SACOGIVA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SEDRE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SEMAC"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SEMADER"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SEMIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SEMISAP"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SEMIVIM"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SFHE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="LMH"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Logis Métropole"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="3F Notre Logis"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Vilogia"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SHLMR"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SIBA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SIDR"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SIPHEM"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SODEGIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SODIAC"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SOGIMA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SIA Habitat (bailleur social)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="SOLIHA (Bailleur social)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="HSA (Bailleur Social)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="DOMOFRANCE (bailleur social)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="UNICIL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="VILOGIA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Domofrance"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Mesolia"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::BAILLEUR_SOCIAL->name.'" WHERE nom="Perigord Habitat"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="Commission de conciliation"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="Conciliateur de justice (en attente)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="Commission Départementale de Conciliation (CDC)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="DDETSPP/DALO ou commission départemental de conciliation"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="DDTM - Commission de conciliation"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="Conciliateur de justice"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="conciliateur de justice"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="Commission de conciliation - DDETS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="Conciliateur de justice"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="DDETS - Conciliation"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="Médiateur urbain"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="commission de conciliation"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONCILIATEURS->name.'" WHERE nom="conciliateur de justice"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="EPCI - CARF"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="EPCI – CAPG"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="EPCI - CACPL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CA Annonay Rhône Agglo"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Rhone Crussol"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CA Arche Agglo"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Val’Eyrieux"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CA Privas-Centre-Ardèche"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Val de Ligne"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Berg et Coiron"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Du Rhône Aux Gorges de l\'Ardèche"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Ardèche Rhône Coiron"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC du Bassin d\'Aubenas"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CDC Montagne Ardéchoise"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Bourges Plus"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="OPAH Sancerre Sologne"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="OPAH Pays Berry Saint Amandois"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="communauté de commune du CAP CORSE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Dijon métropole"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Métropole Chartres"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC du Grand Châteaudun"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC du Perche"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Sicoval"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Communauté de communes du Volvestre"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Bordeaux Métropole"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CA de Béziers-Méditerranée"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC La Domitienne"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CA Hérault-Méditerranée"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC du Pays de Lunel"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Vallée de l\'Hérault"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CD 34 PIG Départemental"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Pays Haut Languedoc et vignoble"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Lodévois et Larzac"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC du Grand Pic Saint-Loup"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="ARS Occitanie - DD34"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="3M MONTPELLIER - MEDITERRANEE - METROPOLE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="SETE AGGLOPOLE MEDITERRANEE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Sud Hérault"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Avant-Monts"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="PETR HAUTES TERRES d\'OC"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC MONTS DE LACAUNE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC BRETAGNE ROMANTIQUE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CCBD"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Grenoble-Alpes Métropole"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Nantes Métropole/SCHS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CCEG"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Cévennes Mont Lozère"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Terres d\'Apcher Margeride Aubrac"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC du Gévaudan"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Haut Allier"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="EPCI"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CD - Terres de Lorraine"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CD - territoire de Briey"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CD - territoire du Lunévillois"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CD - territoire de Longwy"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CCBP"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CCMM"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="MGN"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CAPSO"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CA2BM"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC7V"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CUA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="API"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="BILLOM-CO"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Métropole de Clermont"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="PAYS DE SAINT-ELOY"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="RLV"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="TDM"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Com Com Haut BEARN"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CCLO"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CAPBP sauf Pau"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="PERPIGNAN MEDITERRANEE METROPOLE COMMUNAUTE URBAINE-"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC des Albères, de la Côte Vermeille et de l\'Illibéris"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Roussillon-Conflent"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Pyrénées Cerdagne"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="COMMUNAUTE DE COMMUNES DES ASPRES"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="PYR CATALANES"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="AGLY FENOUILLEDES"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Communauté de Communes Conflent Canigo"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Communauté de communes - Corbières Salanque Méditerranée"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Communauté de communes - Haut-Vallespir"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Communauté de communes - Sud Roussillon"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Communauté de communes - Vallespir"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="COR"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="EMHA - Métropole de Lyon"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="TCO"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Annie PEURON - Directrice Centre Intercommunal Action Sociale - Poher Communauté"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="ARDENNE METROPOLE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CAPEV"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CARENE Saint Nazaire agglomération"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="CC Ventadour Egletons Monédières"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="collectivité de corse"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Commu. Agglo. Arles Crau Camargue Montagnette"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Conseiller Habitat - Haut Léon Communauté"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Erika DAGORN - Chargée Mission Habitat - Concarneau Cornouaille Agglomération"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="La CALI"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Lena BOURHIS - Chargé de Mission Habitat - Poher Communauté"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="M.A.M.P. - CT1 / EAH Marseille"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="M.A.M.P. - CT2 Pays d Aix"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="M.A.M.P. - CT3 Pays Salonais"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="M.A.M.P. - CT4 Pays d’Aubagne et de l’Etoile"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="M.A.M.P. - CT5 Pays Istres Ouest Provence"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="M.A.M.P. - CT6 Pays de Martigues"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Maëlle BONIZEC - conseillère habitat - Communauté de Communes Cap Sizun"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="MBA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="MEL_Service Habitat privé"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="MEL_Service Habitat privé - LILLOIS-NORD"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="MEL_Service Habitat privé - LYS-TOURQUENNOIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="MEL_Service Habitat privé - ROUBAISIS-EST"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="MEL_Service Habitat privé - SUD-WEPPES"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="MEL_Service PLH"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="MEL_unité FSL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Mission Habitat - CC Pays de Landivisiau"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Quimperlé Communauté"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Service CAPV"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Service commun habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Service Habitat - Communauté de Communes Lesneven Côte des Légendes"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Service Habitat - Douarnenez Communauté"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Service Habitat - Morlaix Communauté"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Service habitat privé Métropole de Toulouse"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Service Habitat VGA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="SPL du VELAY"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Terre de Provence Agglomération"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Thibaut ALNET - Chargé de Mission Habitat - Communauté de Communes du Pays Bigouden Sud et du Haut Pays Bigouden"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::EPCI->name.'" WHERE nom="Val de berry - Relogement"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="ALF (OPAH)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="PIG CD"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH GBA Ain"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH CCPA Ain"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH HBA Ain"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Urbanis OPAH Ain"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH RU Coeur de ville Bourg"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH CCRAPC"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="ENERG ETHIQUE 04"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="ALEC Lozère Energie PIG/ OPAH"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="ALTAIR (opérateur OPAH-RU ORTHEZ)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Soliha 26 pour Opah CC ARC"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Soliha 26 plan de sauvegarde Copro Beauregard Annonay"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="DDT Anah"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Anah"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="ANAH"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Citémetrie"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Citémétrie - Cyril BENARD"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Citémétrie - Paula RODRIGUEZ"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Délégation Anah 2A"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="EIE Est"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="EIE Hem roubaix"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="EIE Lille"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Eie Lys"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Eie Nord"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Eie Sud"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Eie Tourcoing"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Eie Weppes"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Nolwenn RAGEL - Chargé de visite eau énergie - Heol"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="GAREL - Opérateur Amelio France renov Sud & Weppes"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Inhari"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Maia Lille Métropole Sud Est"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="MHD CAPA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAC Quimper Cornouaille"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAC43"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Opah"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH DE BASTIA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH Haute Gironde"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH RU Vizille"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH/PIG OC TEHA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="OPAH/PIG Soliha"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Opérateur Amelio - GRAAL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Opérateur CDHAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Opérateur OPAH CAPV"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Operateur OPAH RU La cote Saint André"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Opérateur OPAH RU Voiron"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Opérateur OPAH VCA"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Opérateur OPAH-RU ST Marcellin"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Opérateur Ulisse énergie - dispositif Soleni"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="SOLIHA - Opérateur Amelio France renov"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Soliha (Opérateur PIG/OPAH/Marchés)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Soliha PIG DM"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Urbam"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="URBANIS - AMO-Lot7- Amelio"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Urbanis - OPAH RU Lesneven"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="URBANIS - Opérateur Amelio France renov"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::DISPOSITIF_RENOVATION_HABITAT->name.'" WHERE nom="Expertise & Patrimoine"');

        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD Ain"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD 08"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="conseil départemental"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Conseil Départemental"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Conseil départemental- Habitat logement"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD33"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD38"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD (Département de la Haute-Loire)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD - Département"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD 66"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Adeline KERHERVE - AS CDAS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Anaïs Hervé - Assistante sociale - CDAS Landerneau"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Aude QUELFETER - AS CDAS Quimperlé"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="BREARD Emmanuelle"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="carole ALLAIN - Conseillère Logement CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Caroline Le Gall - AS CDAS Landerneau"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD - Accompagnement social"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD - aménagement / Anah"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD - PIG/Habitat"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD - solidarité"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD / DTS Comminges / Coordonnatrice logement"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD / DTS Lauragais / Coordonnatrice logement"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD / DTS Nord/ Coordonnateur logement"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD / DTS Pays Sud Toulousain / Coordonnatrice logement"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD / DTS Toulouse / Coordonnatrice logement"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD 44 partenariat CARENE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD 64 (uniquement si travaux ANAH-PIG)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD89 UTS AUXERRE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD89 UTS AVALLON"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD89 UTS JOIGNY MIGENNES"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD89 UTS SENS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD89 UTS TONNERRE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD89 UTS TOUCY"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Cécile NEDELEC - Conseillère Logement CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Christelle CATHELOT - AS CDAS Douarnenez"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Claire LE GALL - AS CDAS Concarneau"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CONSEIL DEPARTEMENTAL - sce logement"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CONSEIL DEPARTEMENTAL Service Habitat Privé"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CORNIL Capucine"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Delphine GUYO - Conseillère Logement CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Delphine THEPAUT - Conseillère Logement CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="DEPARTEMENT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Département"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Département - Aide à la pierre Parc privé"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="DEPARTEMENT DT LA ROCHELLE RE AUNIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="DEPARTEMENT DT Rochefort"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="DEPARTEMENT DT Royan"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Département du Rhône"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Dominique GUILLIEC - Conseillère Logement CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="DT Haute Saintonge"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="DT Saintes"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="DT VALS DE SAINTONGE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Elen LE TEUFF - Conseillère Logement CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="CD -  Habitat logement (VEE)"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Geraldine LE BRIS - Conseillère Logement CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="GUYOT Noémie"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Jean Christophe BOISSY - Chargé de visite eau énergie - CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Julie ESCOBAR - AS CDAS Quimperlé"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Lola ROHAN - AS CDAS Landivisiau"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Maëlle APPERE - Conseillère Logement CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Marlène JAMBOU - AS CDAS Quimperlé"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MDS ARRAGEOIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MDS ARTOIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MDS AUDOMAROIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MDS BOULONNAIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MDS CALAISIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MDS HÉNIN"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MDS LENS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MDS MONTREUILLOIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MDS TERNOIS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Morgane Kermorgant - AS CDAS Lannilis"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD ARGENTAT"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD BORT-LES-ORGUES"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD BRIVE CENTRE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD BRIVE EST"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD BRIVE OUEST"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD EGLETONS"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD JUILLAC"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD MEYMAC"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD MEYSSAC"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD TULLE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD USSEL"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="MSD UZERCHE"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="SAIFI Raymonde"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Sylvia COGNAC - AS CDAS Morlaix"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Sylvie PEOCH - AS CDAS de Quimper"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="Tiphaine CARADEC - Conseillère Logement CD29"');
        $this->addSql('UPDATE partner SET type = "'.PartnerType::CONSEIL_DEPARTEMENTAL->name.'" WHERE nom="UTPAS de Villeneuve d Ascq"');
    }

    public function down(Schema $schema): void
    {
    }
}
