<?php

namespace App\Entity\Enum;

enum DocumentType: String
{
    case SITUATION_FOYER_BAIL = 'SITUATION_FOYER_BAIL';
    case SITUATION_FOYER_DPE = 'SITUATION_FOYER_DPE';
    case SITUATION_FOYER_ETAT_DES_LIEUX = 'SITUATION_FOYER_ETAT_DES_LIEUX';
    case SITUATION_DIAGNOSTIC_PLOMB_AMIANTE = 'SITUATION_DIAGNOSTIC_PLOMB_AMIANTE';
    case PROCEDURE_MISE_EN_DEMEURE = 'PROCEDURE_MISE_EN_DEMEURE';
    case PROCEDURE_RAPPORT_DE_VISITE = 'PROCEDURE_RAPPORT_DE_VISITE';
    case PROCEDURE_ARRETE_MUNICIPAL = 'PROCEDURE_ARRETE_MUNICIPAL';
    case PROCEDURE_ARRETE_PREFECTORAL = 'PROCEDURE_ARRETE_PREFECTORAL';
    case PROCEDURE_SAISINE = 'PROCEDURE_SAISINE';
    case BAILLEUR_DEVIS_POUR_TRAVAUX = 'BAILLEUR_DEVIS_POUR_TRAVAUX';
    case BAILLEUR_REPONSE_BAILLEUR = 'BAILLEUR_REPONSE_BAILLEUR';
    case AUTRE = 'AUTRE';
    case SITUATION = 'SITUATION';
    case VISITE = 'VISITE';
}
