<?php

namespace App\Entity\Enum;

enum SuiviCategory: string
{
    case ASK_DOCUMENT = 'ASK_DOCUMENT';
    case ASK_FEEDBACK_SENT = 'ASK_FEEDBACK_SENT';
    case SIGNALEMENT_IS_ACTIVE = 'SIGNALEMENT_IS_ACTIVE';
    case SIGNALEMENT_IS_CLOSED = 'SIGNALEMENT_IS_CLOSED';
    case SIGNALEMENT_IS_REFUSED = 'SIGNALEMENT_IS_REFUSED';
    case SIGNALEMENT_IS_REOPENED = 'SIGNALEMENT_IS_REOPENED';
    case SIGNALEMENT_EDITED_BO = 'SIGNALEMENT_EDITED_BO';
    case SIGNALEMENT_STATUS_IS_SYNCHRO = 'SIGNALEMENT_STATUS_IS_SYNCHRO';
    case AFFECTATION_IS_ACCEPTED = 'AFFECTATION_IS_ACCEPTED';
    case AFFECTATION_IS_REFUSED = 'AFFECTATION_IS_REFUSED';
    case AFFECTATION_IS_CLOSED = 'AFFECTATION_IS_CLOSED';
    case INTERVENTION_IS_REQUIRED = 'INTERVENTION_IS_REQUIRED';
    case INTERVENTION_IS_PLANNED = 'INTERVENTION_IS_PLANNED';
    case INTERVENTION_IS_CANCELED = 'INTERVENTION_IS_CANCELED';
    case INTERVENTION_IS_ABORTED = 'INTERVENTION_IS_ABORTED';
    case INTERVENTION_HAS_CONCLUSION = 'INTERVENTION_HAS_CONCLUSION';
    case INTERVENTION_HAS_CONCLUSION_EDITED = 'INTERVENTION_HAS_CONCLUSION_EDITED';
    case INTERVENTION_IS_RESCHEDULED = 'INTERVENTION_IS_RESCHEDULED';
    case INTERVENTION_PLANNED_REMINDER = 'INTERVENTION_PLANNED_REMINDER';
    case NEW_DOCUMENT = 'NEW_DOCUMENT';
    case DOCUMENT_DELETED_BY_USAGER = 'DOCUMENT_DELETED_BY_USAGER';
    case DOCUMENT_DELETED_BY_PARTNER = 'DOCUMENT_DELETED_BY_PARTNER';
    case MESSAGE_USAGER = 'MESSAGE_USAGER';
    case MESSAGE_ESABORA = 'MESSAGE_ESABORA';
    case MESSAGE_PARTNER = 'MESSAGE_PARTNER';
}
