<?php

namespace App\Entity\Enum;

enum SuiviCategory: string
{
    case ASK_DOCUMENT = 'ASK_DOCUMENT';
    case ASK_FEEDBACK_SENT = 'ASK_FEEDBACK_SENT';
    case SIGNALEMENT_IS_ACTIVE = 'SIGNALEMENT_IS_ACTIVE';
    case SIGNALEMENT_IS_CLOSED = 'SIGNALEMENT_IS_CLOSED';
    case AFFECTATION_IS_ACCEPTED = 'AFFECTATION_IS_ACCEPTED';
    case INTERVENTION_IS_PLANNED = 'INTERVENTION_IS_PLANNED';
    case INTERVENTION_IS_CANCELED = 'INTERVENTION_IS_CANCELED';
    case INTERVENTION_HAS_CONCLUSION = 'INTERVENTION_HAS_CONCLUSION';
    case INTERVENTION_IS_RESCHEDULED = 'INTERVENTION_IS_RESCHEDULED';
    case NEW_DOCUMENT = 'NEW_DOCUMENT';
    case MESSAGE_USAGER = 'MESSAGE_USAGER';
    case SIGNALEMENT_STATUS_IS_SYNCHRO = 'SIGNALEMENT_STATUS_IS_SYNCHRO';
}
