controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

show_file:
    path: /show/{uuid:file}
    controller: App\Controller\FileController::showFile
    defaults:
        _signed: '%feature_secure_uuid_url%'

app_logout_signalement_user:
    path: /logout-suivi

app_logout_signalement_user_success:
    path: /logout-suivi-success
    controller: App\Controller\Security\SecurityController::logoutSignalementUserSuccess