# `special_territory` To define the partners for the special territory
# `authorized_codes_insee` To define the authorized INSEE codes for the special territory
#  Result:
#   - Apply filters on signalement, cartographie and notification for user with role ROLE_ADMIN_TERRITORY
#   - Partner name and insee code partner will be readonly on partner form to make no difference between
#     possible affectation filter and signalement filter
#

parameters:
    special_territory:
     69: # Rhône
      COR: 'COR'
      EMHA - Métropole de Lyon: "EMHA - Métropole de Lyon"
    authorized_codes_insee:
     69:
      COR:
       - "69001"
       - "69006"
       - "69008"
       - "69037"
       - "69054"
       - "69060"
       - "69066"
       - "69070"
       - "69075"
       - "69093"
       - "69102"
       - "69107"
       - "69174"
       - "69130"
       - "69160"
       - "69164"
       - "69169"
       - "69181"
       - "69183"
       - "69188"
       - "69200"
       - "69214"
       - "69217"
       - "69225"
       - "69229"
       - "69234"
       - "69240"
       - "69243"
       - "69248"
       - "69254"
       - "69157"
      EMHA - Métropole de Lyon:
       - "69091"
       - "69091"
       - "69096"
       - "69123"
       - "69149"
       - "69199"
       - "69205"
       - "69290"
       - "69259"
       - "69266"
       - "69381"
       - "69382"
       - "69383"
       - "69384"
       - "69385"
       - "69386"
       - "69387"
       - "69388"
       - "69389"
       - "69901"