config:
  -
    nom_territoire: "BOUCHES-DU-RHONE"
    url_territoire: "habitatindigne13.histologe.fr"
  -
    nom_territoire: "AIN"
    url_territoire: "habitatindigne01.histologe.fr"

  - nom_territoire: "ALPES-MARITIMES"
    url_territoire: "habitat-indigne06.histologe.fr"

  - nom_territoire: "PYRENEES-ATLANTIQUE"
    url_territoire: "habitat-indigne06.histologe.fr"
