name: Playwright Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Symfony CLI
      run: |
        curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash
        sudo apt install symfony-cli

    - name: Start containers
      run: make build

    - name: Curl test
      run: curl -i http://localhost:8080

    - name: Install E2E
      run: make ci-e2e-install

    - name: Test E2E
      run: make ci-e2e-test

##    - uses: actions/setup-node@v4
##      with:
##        node-version: lts/*
##    - name: Install dependencies
##      run: npm ci
##    - name: Install Playwright Browsers
##      run: npx playwright install --with-deps
##    - name: Run Playwright tests
##      run: npx playwright test
##    - uses: actions/upload-artifact@v4
##      if: always()
##      with:
##        name: playwright-report
##        path: playwright-report/
##        retention-days: 30