name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:

env:
  APP_URL: http://localhost:8080
  APP_ENV: test
  APP_SECRET: test_secret_key_for_github_actions
  MAILER_DSN: smtp://signal_logement_mailer:1025
  DATABASE_URL: mysql://signal_logement:signal_logement@signal_logement_mysql:3307/signal_logement_db
  CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
  WKHTMLTOPDF_PATH: wkhtmltopdf
  WKHTMLTOIMAGE_PATH: wkhtmltoimage
  ADMIN_EMAIL: support@signal-logement.beta.gouv.fr
  NOTIFICATIONS_EMAIL: notifications@signal-logement.beta.gouv.fr
  CONTACT_EMAIL: formulaire-contact@signal-logement.beta.gouv.fr
  USER_SYSTEM_EMAIL: admin@signal-logement.beta.gouv.fr
  WIDGET_DATA_KPI_CACHE_EXPIRED_AFTER: 3600
  WIDGET_AFFECTATION_PARTNER_CACHE_EXPIRED_AFTER: 30
  WIDGET_SIGNALEMENT_ACCEPTED_NO_SUIVI_CACHE_EXPIRED_AFTER: 30
  WIDGET_SIGNALEMENT_TERRITOIRE_CACHE_EXPIRED_AFTER: 30
  WIDGET_ESABORA_EVENTS_CACHE_EXPIRED_AFTER: 3600
  FEATURE_OILHI_ENABLE: 0
  FEATURE_BO_SIGNALEMENT_CREATE: 1
  CRON_ENABLE: 0
  MAIL_ENABLE: 0
  MAIL_TEST_ENABLE: 0
  MAIL_TEST_EMAIL: test@example.com
  CSP_ENABLE: 0
  MATOMO_ENABLE: 0
  MAINTENANCE_ENABLE: 0
  MAINTENANCE_BANNER_ENABLE: 0
  MAINTENANCE_BANNER_MESSAGE: 'Une opération de maintenance est en cours'
  AXIOS_TIMEOUT: 30000
  LIMIT_DAILY_RELANCES_BY_REQUEST: 275
  FORMS_SUBMIT_LIMITER_LIMIT: 10
  FORMS_SUBMIT_LIMITER_INTERVAL: '20 minutes'
  API_LIMITER_LIMIT: 60
  API_LIMITER_INTERVAL: '1 minute'
  FEATURE_2FA_EMAIL_ENABLED: 1
  MISE_EN_BERNE_ENABLE: 0
  CLAMAV_SCAN_ENABLE: 0
  HISTORY_TRACKING_ENABLE: 1
  DELAY_MIN_CHECK_NEW_SIGNALEMENT_FILES: 30
  SITES_FACILES_URL: https://signal-logement.beta.gouv.fr/
  FEATURE_SITES_FACILES: 1
  PLATFORM_NAME: "Signal Logement"
  PLATFORM_LOGO: logo-signal-logement.svg
  FEATURE_BANNER_HISTOLOGE: 1
  FEATURE_SECURE_UUID_URL: 1
  FEATURE_PROCONNECT: 0
  PROCONNECT_SCHEME_PROTOCOL: https
  PROCONNECT_DOMAIN: example.com
  PROCONNECT_CLIENT_ID: test_client_id
  PROCONNECT_CLIENT_SECRET: test_client_secret
  FEATURE_EMAIL_RECAP: 1
  FEATURE_SUIVI_ACTION: 1
  FEATURE_ACCUSE_LECTURE: 1
  TRUSTED_PROXIES: 0.0.0.0/0
  S3_ENDPOINT: https://s3.example.com
  S3_KEY: test_key
  S3_SECRET: test_secret
  S3_BUCKET: test_bucket
  S3_URL_BUCKET: https://test-bucket.s3.example.com
  SENTRY_DSN: https://test@sentry.example.com/123
  SENTRY_DSN_FRONT: https://test@sentry.example.com/456
  SENTRY_ENVIRONMENT: test
  SENTRY_TRACES_SAMPLE_RATE: 1.0
  WIREMOCK_HOSTNAME: signal_logement_wiremock
  WIREMOCK_PORT: 8080
  MESSENGER_TRANSPORT_DSN: doctrine://default
  REDIS_URL: redis://signal_logement_redis:6379
  LOCK_DSN: flock
  SIGNATURE_KEY: change_me
  # Configuration PHP-FPM pour les tests
  PHP_FPM_PM_MAX_CHILDREN: 20
  PHP_FPM_PM_START_SERVERS: 5
  PHP_FPM_PM_MIN_SPARE_SERVERS: 2
  PHP_FPM_PM_MAX_SPARE_SERVERS: 10

jobs:
  e2e:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build Docker containers
        run: docker compose build

      - name: Configure PHP-FPM for testing
        run: |
          # Créer un fichier de configuration PHP-FPM temporaire pour les tests
          cat > php-fpm-test.conf << 'EOF'
          [www]
          user = www-data
          group = www-data
          listen = 9000
          listen.owner = www-data
          listen.group = www-data
          listen.mode = 0660
          pm = dynamic
          pm.max_children = 20
          pm.start_servers = 5
          pm.min_spare_servers = 2
          pm.max_spare_servers = 10
          pm.max_requests = 1000
          request_terminate_timeout = 300s
          catch_workers_output = yes
          EOF

      - name: Verify Docker volumes
        run: |
          # Vérifier que le répertoire courant existe et contient les fichiers nécessaires
          echo "Contenu du répertoire courant:"
          ls -la
          echo "Vérification de la présence des fichiers clés:"
          test -f composer.json && echo "✅ composer.json trouvé" || echo "❌ composer.json manquant"
          test -f docker-compose.yml && echo "✅ docker-compose.yml trouvé" || echo "❌ docker-compose.yml manquant"
          test -d src && echo "✅ src/ trouvé" || echo "❌ src/ manquant"

      - name: Generate .env file safely
        run: |
          env | grep -E '^(APP_URL|APP_ENV|APP_SECRET|MAILER_DSN|DATABASE_URL|CORS_ALLOW_ORIGIN|WKHTMLTOPDF_PATH|WKHTMLTOIMAGE_PATH|ADMIN_EMAIL|NOTIFICATIONS_EMAIL|CONTACT_EMAIL|USER_SYSTEM_EMAIL|WIDGET_DATA_KPI_CACHE_EXPIRED_AFTER|WIDGET_AFFECTATION_PARTNER_CACHE_EXPIRED_AFTER|WIDGET_SIGNALEMENT_ACCEPTED_NO_SUIVI_CACHE_EXPIRED_AFTER|WIDGET_SIGNALEMENT_TERRITOIRE_CACHE_EXPIRED_AFTER|WIDGET_ESABORA_EVENTS_CACHE_EXPIRED_AFTER|FEATURE_OILHI_ENABLE|FEATURE_BO_SIGNALEMENT_CREATE|CRON_ENABLE|MAIL_ENABLE|MAIL_TEST_ENABLE|MAIL_TEST_EMAIL|CSP_ENABLE|MATOMO_ENABLE|MAINTENANCE_ENABLE|MAINTENANCE_BANNER_ENABLE|MAINTENANCE_BANNER_MESSAGE|AXIOS_TIMEOUT|LIMIT_DAILY_RELANCES_BY_REQUEST|FORMS_SUBMIT_LIMITER_LIMIT|FORMS_SUBMIT_LIMITER_INTERVAL|API_LIMITER_LIMIT|API_LIMITER_INTERVAL|FEATURE_2FA_EMAIL_ENABLED|MISE_EN_BERNE_ENABLE|CLAMAV_SCAN_ENABLE|HISTORY_TRACKING_ENABLE|DELAY_MIN_CHECK_NEW_SIGNALEMENT_FILES|SITES_FACILES_URL|FEATURE_SITES_FACILES|PLATFORM_NAME|PLATFORM_LOGO|FEATURE_BANNER_HISTOLOGE|FEATURE_SECURE_UUID_URL|FEATURE_PROCONNECT|PROCONNECT_SCHEME_PROTOCOL|PROCONNECT_DOMAIN|PROCONNECT_CLIENT_ID|PROCONNECT_CLIENT_SECRET:|FEATURE_EMAIL_RECAP|FEATURE_SUIVI_ACTION|FEATURE_ACCUSE_LECTURE|TRUSTED_PROXIES|S3_ENDPOINT|S3_KEY|S3_SECRET|S3_BUCKET|S3_URL_BUCKET|SENTRY_DSN|SENTRY_DSN_FRONT|SENTRY_ENVIRONMENT|SENTRY_TRACES_SAMPLE_RATE|WIREMOCK_HOSTNAME|WIREMOCK_PORT|MESSENGER_TRANSPORT_DSN|REDIS_URL|LOCK_DSN|SIGNATURE_KEY|PHP_FPM_PM_MAX_CHILDREN|PHP_FPM_PM_START_SERVERS|PHP_FPM_PM_MIN_SPARE_SERVERS|PHP_FPM_PM_MAX_SPARE_SERVERS)=' \
          | while IFS='=' read -r key value; do
              safe_value=$(printf "%s" "$value" | sed 's/"/\\"/g')
              echo "${key}=\"${safe_value}\""
            done > .env

      - name: Start Docker containers
        run: docker compose up -d

      - name: Force restart containers and verify volumes
        run: |
          echo "Arrêt des conteneurs..."
          docker compose down
          echo "Redémarrage des conteneurs..."
          docker compose up -d
          echo "Attente que les conteneurs soient prêts..."
          sleep 15
          echo "Vérification du montage des volumes..."
          docker compose exec -T signal_logement_phpfpm ls -la /app/ || {
            echo "❌ Problème de montage détecté, tentative de correction..."
            echo "Création explicite du répertoire /app..."
            docker compose exec -T signal_logement_phpfpm mkdir -p /app
            docker compose exec -T signal_logement_phpfpm chown -R www-data:www-data /app
            echo "Vérification des permissions..."
            docker compose exec -T signal_logement_phpfpm ls -la /app/ || echo "❌ Toujours pas accessible"
          }

      - name: Restart PHP-FPM with test configuration
        run: |
          echo "Copie de la configuration PHP-FPM de test..."
          # Copier la configuration de test dans le conteneur
          docker cp php-fpm-test.conf signal_logement_phpfpm:/usr/local/etc/php-fpm.d/www.conf
          echo "Redémarrage du conteneur PHP-FPM..."
          # Redémarrer le conteneur complet pour s'assurer que la configuration est prise en compte
          docker compose restart signal_logement_phpfpm
          echo "Attente que PHP-FPM redémarre..."
          sleep 15
          echo "Vérification que PHP-FPM fonctionne..."
          docker compose ps signal_logement_phpfpm
          echo "Logs PHP-FPM après redémarrage:"
          docker compose logs signal_logement_phpfpm | tail -10

      - name: Verify container volumes
        run: |
          echo "Vérification du montage des volumes dans le conteneur PHP-FPM:"
          docker compose exec -T signal_logement_phpfpm ls -la /app/ || echo "❌ Répertoire /app/ non accessible"
          docker compose exec -T signal_logement_phpfpm test -f /app/composer.json && echo "✅ composer.json accessible" || echo "❌ composer.json non accessible"
          docker compose exec -T signal_logement_phpfpm test -d /app/src && echo "✅ src/ accessible" || echo "❌ src/ non accessible"
          echo "Vérification du répertoire de travail:"
          docker compose exec -T signal_logement_phpfpm pwd

      - name: Verify PHP-FPM is working
        run: |
          echo "Vérification que PHP-FPM fonctionne correctement..."
          # Vérifier que le conteneur est en cours d'exécution
          docker compose ps signal_logement_phpfpm | grep "Up" || {
            echo "❌ Conteneur PHP-FPM n'est pas en cours d'exécution"
            docker compose logs signal_logement_phpfpm
            exit 1
          }
          # Vérifier que PHP-FPM répond
          docker compose exec -T signal_logement_phpfpm php -v || {
            echo "❌ PHP n'est pas accessible dans le conteneur"
            exit 1
          }
          echo "✅ PHP-FPM fonctionne correctement"

      - name: Wait for PHP container to be ready
        run: |
          docker compose exec -T signal_logement_phpfpm bash -c 'until php -v > /dev/null; do sleep 1; done'

      - name: Install PHP dependencies
        run: |
          docker compose exec -T signal_logement_phpfpm composer install --no-interaction --optimize-autoloader
          docker compose exec -T signal_logement_phpfpm composer install --working-dir=tools/php-cs-fixer --no-interaction --optimize-autoloader
          docker compose exec -T signal_logement_phpfpm composer install --working-dir=tools/wiremock --no-interaction --optimize-autoloader
          docker compose exec -T signal_logement_phpfpm composer require symfony/redis-messenger --no-interaction

      - name: Build frontend assets
        run: |
          docker compose exec -T signal_logement_phpfpm npm ci
          docker compose exec -T signal_logement_phpfpm npm run build

      - name: Verify frontend assets
        run: |
          # Vérifier que les assets sont bien construits
          echo "Vérification des assets frontend:"
          docker compose exec -T signal_logement_phpfpm ls -la /app/public/build/ 2>/dev/null || echo "❌ Répertoire public/build/ non accessible"
          # Vérifier que les fichiers JavaScript sont présents
          docker compose exec -T signal_logement_phpfpm find /app/public -name "*.js" -type f 2>/dev/null | head -5 || echo "❌ Aucun fichier JS trouvé"
          echo "Vérification alternative depuis l'extérieur du conteneur:"
          ls -la public/build/ 2>/dev/null || echo "❌ Répertoire public/build/ non accessible depuis l'hôte"

      - name: Cache clear & warmup
        run: |
          docker compose exec -T signal_logement_phpfpm php bin/console cache:clear --env=dev --no-warmup
          docker compose exec -T signal_logement_phpfpm php bin/console cache:warmup --env=dev

      - name: Clear cache and sessions
        run: |
          echo "Nettoyage complet du cache et des sessions..."
          docker compose exec -T signal_logement_phpfpm php bin/console cache:clear --env=dev --no-warmup
          docker compose exec -T signal_logement_phpfpm php bin/console cache:warmup --env=dev
          # Nettoyer les sessions
          docker compose exec -T signal_logement_phpfpm rm -rf var/sessions/* || true
          echo "Cache et sessions nettoyés"

      - name: Init database
        run: |
          docker compose exec -T signal_logement_phpfpm php bin/console doctrine:database:drop --force --no-interaction || true
          docker compose exec -T signal_logement_phpfpm php bin/console doctrine:database:create --no-interaction
          docker compose exec -T signal_logement_phpfpm php bin/console messenger:setup-transports --no-interaction
          docker compose exec -T signal_logement_phpfpm php bin/console doctrine:migrations:migrate --no-interaction
          docker compose exec -T signal_logement_phpfpm php bin/console doctrine:fixtures:load --no-interaction

      - name: Wait for application to be ready
        run: |
          # Attendre que l'application soit accessible
          until curl -f http://localhost:8080/signalement > /dev/null 2>&1; do
            echo "Waiting for application to be ready..."
            sleep 5
          done
          echo "Application is ready!"

      - name: Install Node.js for Playwright
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright dependencies
        working-directory: tests/e2e
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: tests/e2e
        run: npx playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e/test-results/
          retention-days: 30

      - name: Check server logs
        if: ${{ always() }}
        run: docker compose logs signal_logement_phpfpm

      - name: Check nginx logs
        if: ${{ always() }}
        run: docker compose logs signal_logement_nginx

      - name: Check build output inside container
        if: ${{ always() }}
        run: |
          echo "=== DEBUG: Informations sur le conteneur ==="
          docker compose ps
          echo "=== DEBUG: Volumes du conteneur ==="
          docker inspect signal_logement_phpfpm | grep -A 10 -B 5 "Mounts"
          echo "=== DEBUG: Tentative d'accès au conteneur ==="
          docker compose exec signal_logement_phpfpm bash -c "ls -la /" || echo "❌ Impossible d'exécuter bash"
          echo "=== DEBUG: Vérification du répertoire de travail ==="
          docker compose exec signal_logement_phpfpm pwd || echo "❌ Impossible d'obtenir le répertoire de travail"
          echo "=== DEBUG: Tentative d'accès à /app ==="
          docker compose exec signal_logement_phpfpm ls -la /app 2>/dev/null || echo "❌ Répertoire /app non accessible"

      - name: Debug container issues
        if: ${{ always() }}
        run: |
          echo "=== DIAGNOSTIC COMPLET ==="
          echo "1. État des conteneurs:"
          docker compose ps -a
          echo ""
          echo "2. Logs du conteneur PHP-FPM:"
          docker compose logs signal_logement_phpfpm | tail -20
          echo ""
          echo "3. Configuration des volumes:"
          docker inspect signal_logement_phpfpm | jq '.[0].Mounts' 2>/dev/null || docker inspect signal_logement_phpfpm | grep -A 20 "Mounts"
          echo ""
          echo "4. Tentative d'accès au conteneur:"
          docker compose exec -T signal_logement_phpfpm whoami 2>/dev/null || echo "❌ Impossible d'exécuter des commandes dans le conteneur"
          echo ""
          echo "5. Vérification du répertoire de travail:"
          docker compose exec -T signal_logement_phpfpm pwd 2>/dev/null || echo "❌ Impossible d'obtenir le répertoire de travail"
          echo ""
          echo "6. Tentative d'accès à /app:"
          docker compose exec -T signal_logement_phpfpm ls -la /app 2>/dev/null || echo "❌ Répertoire /app non accessible"
          echo ""
          echo "7. Vérification depuis l'hôte:"
          ls -la | head -10
          echo ""
          echo "8. Test de montage manuel:"
          docker run --rm -v $(pwd):/test alpine ls -la /test | head -5 || echo "❌ Montage manuel échoué"

